apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grey
  name: grey
spec:
  containers:
  - image: nginx:1.15
    name: grey
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
