apiVersion: v1
kind: Pod
metadata:
  name: nginx-kusc00401
spec:
  containers:
  - name: nginx-kusc00401
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    minikube.k8s.io/name: minikube
