apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: green-nginx
  name: green-nginx
spec:
  containers:
  - image: nginx
    name: green-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
