apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipod
  name: multipod
spec:
  containers:
  - image: nginx
    name: container-1
  - image: redis
    name: container-2
  - image: alpine
    name: container-3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
